services:
  postgres_mtls:
    image: postgres-mtls
    container_name: postgres-mtls
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_mtls:/var/lib/postgresql/data
volumes:
  postgres_mtls:
    name: postgres_mtls
networks:
  default:
    name: postgres_mtls

